/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;

/**
 *
 * @author valer
 */
public class jfrmConfiguración extends javax.swing.JFrame {

    /**
     * Creates new form jfrmConfiguración
     */
    public jfrmConfiguración() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblMensaje = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblCantidadPasajeros = new javax.swing.JLabel();
        lblCantidadSobrecargos = new javax.swing.JLabel();
        lblNombrePiloto = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        txtPasajeros = new javax.swing.JTextField();
        txtSobrecargos = new javax.swing.JTextField();
        txtPiloto = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configuración");
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(28, 33, 53));

        jPanel2.setBackground(new java.awt.Color(68, 115, 142));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Configuración");

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblMensaje.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(0, 0, 0));
        lblMensaje.setText("Para generar aviones por favor llene todos los campos");

        lblModelo.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        lblModelo.setForeground(new java.awt.Color(53, 79, 100));
        lblModelo.setText("Modelo");

        lblCantidadPasajeros.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        lblCantidadPasajeros.setForeground(new java.awt.Color(53, 79, 100));
        lblCantidadPasajeros.setText("Cantidad de pasajeros");

        lblCantidadSobrecargos.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        lblCantidadSobrecargos.setForeground(new java.awt.Color(53, 79, 100));
        lblCantidadSobrecargos.setText("Cantidad de sobrecargos");

        lblNombrePiloto.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        lblNombrePiloto.setForeground(new java.awt.Color(53, 79, 100));
        lblNombrePiloto.setText("Nombre del piloto");

        txtModelo.setBackground(new java.awt.Color(255, 255, 255));
        txtModelo.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        txtModelo.setForeground(new java.awt.Color(204, 204, 204));
        txtModelo.setText("  Texto");
        txtModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtModeloMousePressed(evt);
            }
        });

        txtPasajeros.setBackground(new java.awt.Color(255, 255, 255));
        txtPasajeros.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        txtPasajeros.setForeground(new java.awt.Color(204, 204, 204));
        txtPasajeros.setText("  Cantidad");
        txtPasajeros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtPasajeros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPasajerosMousePressed(evt);
            }
        });

        txtSobrecargos.setBackground(new java.awt.Color(255, 255, 255));
        txtSobrecargos.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        txtSobrecargos.setForeground(new java.awt.Color(204, 204, 204));
        txtSobrecargos.setText("  Cantidad");
        txtSobrecargos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtSobrecargos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtSobrecargosMousePressed(evt);
            }
        });

        txtPiloto.setBackground(new java.awt.Color(255, 255, 255));
        txtPiloto.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 12)); // NOI18N
        txtPiloto.setForeground(new java.awt.Color(204, 204, 204));
        txtPiloto.setText("  Texto");
        txtPiloto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtPiloto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPilotoMousePressed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCantidadPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCantidadSobrecargos, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombrePiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModelo)
                            .addComponent(txtPasajeros)
                            .addComponent(txtSobrecargos)
                            .addComponent(txtPiloto))
                        .addGap(27, 27, 27))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblMensaje)
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelo)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lblCantidadPasajeros)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSobrecargos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidadSobrecargos))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombrePiloto)
                    .addComponent(txtPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
        public boolean validaciones() {
        byte estado = 1;
        if (txtModelo.getText().compareTo("  Texto") == 0 || txtModelo.getText().compareTo("") == 0) {
            txtModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 0, 0)));
            estado = 0;
        } else {
            txtModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        }
        if (txtPasajeros.getText().compareTo("  Cantidad") == 0 || txtPasajeros.getText().compareTo("") == 0) {
            txtPasajeros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 0, 0)));
            estado = 0;
        } else {
            txtPasajeros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        }
        if (txtSobrecargos.getText().compareTo("  Cantidad") == 0 || txtSobrecargos.getText().compareTo("") == 0) {
            txtSobrecargos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 0, 0)));
            estado = 0;
        } else {
            txtSobrecargos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        }
        if (txtPiloto.getText().compareTo("  Texto") == 0 || txtPiloto.getText().compareTo("") == 0) {
            txtPiloto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 0, 0)));
            estado = 0;
        } else {
            txtPiloto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        }

        if (estado == 0) {
            return false;
        } else {
            return true;
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        validaciones();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtModeloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtModeloMousePressed
        txtModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 115, 142)));
        txtPasajeros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtSobrecargos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtPiloto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        if (txtModelo.getText().equals("  Texto")) {
            txtModelo.setText("");
            txtModelo.setForeground(Color.BLACK);

            txtPasajeros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
            txtSobrecargos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
            txtPiloto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        }
        if (txtPasajeros.getText().equals("")) {
            txtPasajeros.setText("  Cantidad");
            txtPasajeros.setForeground(new java.awt.Color(204, 204, 204));
            txtPasajeros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        }

        if (txtSobrecargos.getText().equals("")) {
            txtSobrecargos.setText("  Cantidad");
            txtSobrecargos.setForeground(new java.awt.Color(204, 204, 204));
            txtSobrecargos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        }

        if (txtPiloto.getText().equals("")) {
            txtPiloto.setText("  Texto");
            txtPiloto.setForeground(new java.awt.Color(204, 204, 204));
            txtPiloto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        }

    }//GEN-LAST:event_txtModeloMousePressed

    private void txtPasajerosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasajerosMousePressed
        txtPasajeros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 115, 142)));
        txtSobrecargos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtPiloto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        if (txtPasajeros.getText().equals("  Cantidad")) {
            txtPasajeros.setText("");
            txtPasajeros.setForeground(Color.BLACK);

            txtSobrecargos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
            txtPiloto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
            txtModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        }

        if (txtSobrecargos.getText().equals("")) {
            txtSobrecargos.setText("  Cantidad");
            txtSobrecargos.setForeground(new java.awt.Color(204, 204, 204));
            txtSobrecargos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        }

        if (txtPiloto.getText().equals("")) {
            txtPiloto.setText("  Texto");
            txtPiloto.setForeground(new java.awt.Color(204, 204, 204));
            txtPiloto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        }

        if (txtModelo.getText().equals("")) {
            txtModelo.setText("  Texto");
            txtModelo.setForeground(new java.awt.Color(204, 204, 204));
            txtModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        }
    }//GEN-LAST:event_txtPasajerosMousePressed

    private void txtSobrecargosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSobrecargosMousePressed
        txtSobrecargos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 115, 142)));
        txtPiloto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtPasajeros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        if (txtSobrecargos.getText().equals("  Cantidad")) {
            txtSobrecargos.setText("");
            txtSobrecargos.setForeground(Color.BLACK);

            txtPiloto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
            txtModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
            txtPasajeros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        }

        if (txtPiloto.getText().equals("")) {
            txtPiloto.setText("  Texto");
            txtPiloto.setForeground(new java.awt.Color(204, 204, 204));
            txtPiloto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        }

        if (txtModelo.getText().equals("")) {
            txtModelo.setText("  Texto");
            txtModelo.setForeground(new java.awt.Color(204, 204, 204));
            txtModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        }

        if (txtPasajeros.getText().equals("")) {
            txtPasajeros.setText("  Cantidad");
            txtPasajeros.setForeground(new java.awt.Color(204, 204, 204));
            txtPasajeros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        }
    }//GEN-LAST:event_txtSobrecargosMousePressed

    private void txtPilotoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPilotoMousePressed
        txtPiloto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 115, 142)));
        txtModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtPasajeros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtSobrecargos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        if (txtPiloto.getText().equals("  Texto")) {
            txtPiloto.setText("");
            txtPiloto.setForeground(Color.BLACK);

            txtModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
            txtPasajeros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
            txtSobrecargos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        }

        if (txtModelo.getText().equals("")) {
            txtModelo.setText("  Texto");
            txtModelo.setForeground(new java.awt.Color(204, 204, 204));
            txtModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        }

        if (txtPasajeros.getText().equals("")) {
            txtPasajeros.setText("  Cantidad");
            txtPasajeros.setForeground(new java.awt.Color(204, 204, 204));
            txtPasajeros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        }

        if (txtSobrecargos.getText().equals("")) {
            txtSobrecargos.setText("  Cantidad");
            txtSobrecargos.setForeground(new java.awt.Color(204, 204, 204));
            txtSobrecargos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        }
    }//GEN-LAST:event_txtPilotoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmConfiguración.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmConfiguración.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmConfiguración.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmConfiguración.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmConfiguración().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCantidadPasajeros;
    private javax.swing.JLabel lblCantidadSobrecargos;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblNombrePiloto;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPasajeros;
    private javax.swing.JTextField txtPiloto;
    private javax.swing.JTextField txtSobrecargos;
    // End of variables declaration//GEN-END:variables
}
