/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Logica.clsAviones;
import Logica.clsListasAviones;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author valer
 */
public class jfrmGenerarAviones extends javax.swing.JFrame {

    /**
     * Creates new form jfrmGenerarAviones
     */
    public jfrmGenerarAviones() {
        initComponents();
        inicializarPopUpMenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuTabla = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAviones = new javax.swing.JTable();
        btnIniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblAviones.setBackground(new java.awt.Color(255, 255, 255));
        tblAviones.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        tblAviones.setForeground(new java.awt.Color(0, 0, 0));
        tblAviones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Modelo", "Cantidad de pasajeros", "Cantidad de sobrecargos", "Nombre de Piloto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblAviones.setGridColor(new java.awt.Color(204, 204, 204));
        tblAviones.setName(""); // NOI18N
        tblAviones.setRowHeight(22);
        tblAviones.setSelectionBackground(new java.awt.Color(232, 114, 69));
        tblAviones.setShowGrid(true);
        jScrollPane1.setViewportView(tblAviones);

        btnIniciar.setBackground(new java.awt.Color(53, 79, 100));
        btnIniciar.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciar.setText("Deseo comenzar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(53, 79, 100));
        jLabel1.setText("Para empezar la simulación debe añadir información de los aviones a controlar en la tabla.");

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(53, 79, 100));
        jLabel2.setText("*Debe ingresar mínimo 10 aviones.");

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(53, 79, 100));
        jLabel3.setText("*Para añadir más de 10 aviones puede verlo en las opciones de la tabla presionando click derecho.");

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(53, 79, 100));
        jLabel4.setText("*El máximo de aviones para empezar el simulador es de 25");

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(68, 115, 142));
        jLabel5.setText("Bienvenido");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1038, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1038, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(453, 453, 453)
                        .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void leerDatos() {
        clsListasAviones listaAviones = new clsListasAviones();
        DefaultTableModel modelo = (DefaultTableModel) tblAviones.getModel();

        //Obtengo la cantidad de filas de la tabla
        int cantidadFilas = modelo.getRowCount();
        
        boolean validacion = true; //Cambiará a false en caso de que encuentre alguna fila o celda vacía de la table
        for (int i = 0; i < cantidadFilas; i++) {

            if (modelo.getValueAt(i, 0) == null || modelo.getValueAt(i, 1).toString() == null || modelo.getValueAt(i, 2) == null || modelo.getValueAt(i, 3) == null) {
                if (validacion) {
                    JOptionPane.showMessageDialog(null, "Debe llenar todos los campos", "Problema", JOptionPane.ERROR_MESSAGE);
                    validacion = false;
                }

            } else {
                String modeloAvion = modelo.getValueAt(i, 0).toString();
                String pasajeros = modelo.getValueAt(i, 1).toString();
                String sobrecargos = modelo.getValueAt(i, 2).toString();
                String nombrePiloto = modelo.getValueAt(i, 3).toString();
                clsAviones avion = new clsAviones(modeloAvion, Integer.parseInt(pasajeros), Integer.parseInt(sobrecargos), nombrePiloto);
                //Añado un avión a la lista central
                listaAviones.añadirCentral(avion);
            }
        }

        if (validacion) {
            //Se abre la ventana principal del simulador
            jfrmPrincipal ventana = new jfrmPrincipal();
            ventana.setVisible(true);

            //Se cierra la ventana de inicio
            jfrmIniciarSimulacion ventanaAnterior = new jfrmIniciarSimulacion();
            ventanaAnterior.dispose();

            //Se cierra la ventana actual
            this.dispose();
        }
    }

    public boolean validaciones(){
        DefaultTableModel modelo = (DefaultTableModel) tblAviones.getModel();
        
        if (modelo.getRowCount() < 10) {
            JOptionPane.showMessageDialog(null, "Debe ingresar mínimo 10 aviones", "Problema", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (modelo.getRowCount() > 25){
            JOptionPane.showMessageDialog(null, "Debe ingresar máximo 25 aviones para el inicio de la simulación", "Problema", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            return true;
        }
        
    }

    public void inicializarPopUpMenu() {
        //Se crean las opciones para el popup menu
        JMenuItem agregar = new JMenuItem("Añadir fila");
        JMenuItem eliminar = new JMenuItem("Borrar fila");

        //Se añaden las opciones creadas al popup menu
        menuTabla.add(agregar);
        menuTabla.addSeparator();
        menuTabla.add(eliminar);

        //Se le añade a la tabla el popup menu
        tblAviones.setComponentPopupMenu(menuTabla);

        //Se le agrega las funcionalidades de agregar y eliminar filas a las opciones del popup menu
        agregar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                DefaultTableModel modelo = (DefaultTableModel) tblAviones.getModel();
                modelo.addRow(new Object[]{null, null, null, null});//Se añade una fila vacía
            }
        });

        eliminar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                DefaultTableModel modelo = (DefaultTableModel) tblAviones.getModel();
                int fila = tblAviones.getSelectedRow();
                if (fila == -1) {    //Si el método getSelectedRow retorna -1 es porque no hay una fila seleccionada que borrar
                    JOptionPane.showMessageDialog(null, "Para eliminar una fila debe seleccionarla", "Información", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    modelo.removeRow(fila);
                }
            }
        });
    }


  
    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        if (validaciones() == true) {
            leerDatos();

            /*//Se abre la ventana principal del simulador
            jfrmPrincipal ventana = new jfrmPrincipal();
            ventana.setVisible(true);

            //Se cierra la ventana de inicio
            jfrmIniciarSimulacion ventanaAnterior = new jfrmIniciarSimulacion();
            ventanaAnterior.dispose();

            //Se cierra la ventana actual
            this.dispose();*/
        }

    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmGenerarAviones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmGenerarAviones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmGenerarAviones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmGenerarAviones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmGenerarAviones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu menuTabla;
    private javax.swing.JTable tblAviones;
    // End of variables declaration//GEN-END:variables
}
